version: '3'
services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
  springboot-docker-maven-compose:
    image: docker.demo.maven:1
    depends_on:
      - docker-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-maven-compose
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
      - spring.profiles.active=local