apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker-maven
  labels:
     name: spring-boot-docker-maven
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
     app: spring-boot-docker-maven

