apiVersion: skaffold/v1
kind: Config
metadata:
  name: docker.demo
build:
  artifacts:
    - image: spring-boot-docker-maven
      jib: {}
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s-deployment.yml
      - k8s-service.yml

